#ifndef ERRORS_H
#define ERRORS_H

// PolicyApplier

#define CONFIG_NOT_FOUND 0x1
#define CONFIG_SYNTAX_ERROR 0x2
#define UNABLE_TO_WRITE_TO_LOG_FILE 0x3
#define ERROR_WHILE_WRITING_TO_LOG 0x4
#define INVALID_PARAMETER_IN_CONFIG_FILE 0x5
#define INCOMPLETE_CONFIG 0x6
#define CRITERION_CONFIG_SYNTAX_ERROR 0x7
#define CRITERIONS_NOT_DEFINED 0x8
#define POLICIES_NOT_DEFINED 0x9

// Set, Show
#define UNABLE_TO_CONNECT_TO_QUAGGA_SHELL 0x1001

#endif // ERRORS_H
